name: Continuous Integration (Unstable)

on:
    schedule:
        -
            cron: "0 4 * * *" # Run every day at 4am
    workflow_dispatch: ~

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}-unstable
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    e2e-unstable:
        name: End-to-end tests (Unstable)
        uses: ./.github/workflows/ci_e2e-unstable.yaml
    packages-unstable:
        name: Packages (Unstable)
        uses: ./.github/workflows/ci_packages-unstable.yaml
        with:
            type: minimal
